Laravel/Tarea copia xD/hiro/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	toastr()->error('An error has occurred please try again later.');
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/usuarios/consulta', 'Users@consulta');
Route::post('/usuarios/mostrar','Users@mostrar');
Route::resource('/usuarios', 'Users');

Laravel/Tarea copia xD/hiro/app/Competencias.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Competencias extends Model
{
    //
}

Laravel/Tarea copia xD/hiro/app/Usuarios.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Usuarios extends Model
{
    //
}

Laravel/Tarea copia xD/hiro/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

Laravel/Tarea copia xD/hiro/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

Laravel/Tarea copia xD/hiro/app/Http/Controllers/Users.php
<?php

namespace App\Http\Controllers;

use App\Usuarios;
use App\Procedures\UsuariosProcedure;
use Illuminate\Http\Request;

class Users extends Controller
{
    //Se almacenará en una propiedad  heredable.
    protected $UsuariosProcedure;
    //En el método constructor, se pasará para poder utilizarlo cuando desee dentro de la clase.
    /*Fn: Constructor de la Clase
    @param: Objeto de tipo UsuariosProcedure
    @return: na */    
    public function __construct(UsuariosProcedure $UsuariosProcedure)
    {
        $this->UsuariosProcedure = $UsuariosProcedure;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */    
    /*Fn: Mostrar vista principal de Usuario
    @param: na
    @return: Vista Principal */ 
    public function index()
    {
        return view('usuarios.index');    
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    /*Fn: Mostrar vista del formulario de ingreso de Usuario
    @param: na
    @return: Vista del Formulario de Create */     
    public function create()
    {
        return view('usuarios.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    /*Fn: Crea un nuevo usuario
    @param: Objeto de tipo Request
    @return: Vista Principal */     
    public function store(Request $request)
    {
        $array = [$request->name, $request->lastname, $request->colonia, $request->email, $request->competition, $request->description];
        $this->UsuariosProcedure->insertarUsuariosCompetencia($array);
        alert()->message('', 'Registro efectuado con exito')->persistent('Ok');
        return redirect()->route('usuarios.create');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function consulta()
    {
        //Almaceno el resultado en una variable $usuarios, llamo a la propiedad y le pido el método que llamara al procedimiento almacenado.
        $UCS = $this->UsuariosProcedure->getUsuariosCompetencias();
        $usuarios = $this->UsuariosProcedure->getUsuarios();
        $competencias = $this->UsuariosProcedure->getCompetencias();
        /*Se lo manda finalmente a una vista, con la variable :) esta se volvió en un arreglo asociativo, así que solo tendría que llamar a los campos desde la vista algo así {{$departamentos[0]->Codigo_Departamento}} y hacerle un foreach */
        return view('usuarios.consulta', compact(['UCS', 'usuarios', 'competencias']));  
    }

    /**
     * Display the specified resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function mostrar(Request $request)
    {
        $user = $request->user;
        $competition = $request->competencia;

        if (($user > 0) && ($competition > 0)) {
            $array = [$user, $competition];
            $UCS = $this->UsuariosProcedure->getUsuariosCompetenciaporUsuariosCompetencias($array);
            $usuarios = $this->UsuariosProcedure->getUsuarios();
            $competencias = $this->UsuariosProcedure->getCompetencias();
            toastr()->success('Consulta Ejecutada con exito', 'Exito!');
        }else{
            if ($user > 0) {
                $array = [$user];
                $UCS = $this->UsuariosProcedure->getUsuariosCompetenciaporUsuario($array);
                $usuarios = $this->UsuariosProcedure->getUsuarios();
                $competencias = $this->UsuariosProcedure->getCompetencias();
                toastr()->success('Consulta Ejecutada con exito', 'Exito!');
            }else{
                if ($competition > 0) {
                    $array = [$competition];
                    $UCS = $this->UsuariosProcedure->getUsuariosCompetenciaporCompetencia($array);
                    $usuarios = $this->UsuariosProcedure->getUsuarios();
                    $competencias = $this->UsuariosProcedure->getCompetencias();
                    toastr()->success('Consulta Ejecutada con exito', 'Exito!');     
                }else{
                    $UCS = $this->UsuariosProcedure->getUsuariosCompetencias();
                    $usuarios = $this->UsuariosProcedure->getUsuarios();
                    $competencias = $this->UsuariosProcedure->getCompetencias();
                    toastr()->error('Seleccione un Alumno o Competencia para realizar la consulta', 'Error!');
                }
            }
        }

        return view('usuarios.consulta', compact(['UCS', 'usuarios', 'competencias']));  
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Usuarios  $usuarios
     * @return \Illuminate\Http\Response
     */
    public function show(Usuarios $usuarios)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Usuarios  $usuarios
     * @return \Illuminate\Http\Response
     */
    public function edit(Usuarios $usuarios)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Usuarios  $usuarios
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Usuarios $usuarios)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Usuarios  $usuarios
     * @return \Illuminate\Http\Response
     */
    public function destroy(Usuarios $usuarios)
    {
        //
    }
}

Laravel/Tarea copia xD/hiro/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

Laravel/Tarea copia xD/hiro/resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

Laravel/Tarea copia xD/hiro/resources/views/usuarios/consulta.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Consultar Usuarios</title>
  <!-- CSRF Token -->
  <meta name="csrf-token" content="{{ csrf_token() }}">

  <!-- Scripts -->
  <script src="{{ asset('js/app.js') }}" defer></script>

  <!-- Fonts -->
  <link rel="dns-prefetch" href="//fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

  <!-- Styles -->
  <link href="{{ asset('css/app.css') }}" rel="stylesheet">
  <link href="{{ asset('css/style.css') }}" rel="stylesheet">   
  @toastr_css
</head>
<body>
  <nav class="navbar navbar-dark bg-dark navbar-expand-sm">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-list-2" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar-list-2">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{{ route('usuarios.index') }}">Inicio <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Gestion alumno
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{{ route('usuarios.create') }}">Registro de Alumnos</a>
            <a class="dropdown-item" href="#">Detalles de Alumnos</a>
          </div>
        </li>       
        <li class="nav-item active">
          <a class="nav-link" href="{{ asset('/usuarios/consulta') }}">Consulta</a>
        </li>   
      </ul>
    </div>
  </nav>
  <br>
  <div class="d-flex justify-content-center">
   <div class="col-11">
    <div class="card mb-4">
      <!-- <div class="card-header"><i class="fas fa-table mr-1"></i>Registro de Alumnos</div> -->
      <div class="card-body">
        <div class="container-fluid">
          <div class="card mb-4">
            <!-- <div class="card-header"><i class="fas fa-table mr-1"></i>Registro de Alumnos</div> -->
            <div class="card-body">
              <form method="POST" action="{{ asset('/usuarios/mostrar') }}">
                @csrf
                <div class="container-fluid">
                  <div class="row">
                    <div class="col-sm-5 col-md-6">
                      <div class="form-group">
                        <table cellpadding="10" cellspacing="3">
                          <tr>
                            <td>Alumnos:</td>
                            <td width="100%">
                              <select name="user" class="form-control">
                                <option value="">--Seleccione--</option>
                                @foreach($usuarios as $users)
                                <option value="{{$users->usuario_id}}">{{$users->nombres}} {{$users->apellidos}}</option>
                                @endforeach                              
                              </select>
                            </td>
                          </tr>
                          <tr>
                            <td colspan="2">
                              <table class="tabla1">
                                <tr>
                                  <td align="left">Cantidad de Competencias</td>
                                  <td align="right" width="403px"><input type="number" name="" max="10" min="1"></td>
                                </tr>
                              </table>
                            </td>
                          </tr>                    
                        </table>
                      </div>    
                    </div>
                    <div class="col-sm-5 offset-sm-2 col-md-6 offset-md-0">
                      <div class="form-group">
                        <table cellpadding="10" cellspacing="3">
                          <tr>
                            <td>Competencia:</td>
                            <td width="100%">
                              <select name="competencia" class="form-control">
                                <option value="">--Seleccione--</option>
                                @foreach($competencias as $comp)
                                <option value="{{$comp->competencia_id}}">{{$comp->nombre}}</option>
                                @endforeach                                 
                              </select>
                            </td>
                          </tr>
                          <tr>
                            <td colspan="2">
                              <table class="tabla" cellspacing="3">
                                <tr>
                                  <td width="50%"><a href="#"><button type="submit" class="btn btn-block btn-lg btn-secondary">Restablecer</button></a></td>
                                  <td width="50%">
                                    <input type="submit" name="Enviar" value="Consultar" class="btn btn-block btn-lg btn-dark">
                                  </tr>
                                </table>
                              </td>
                            </tr>                          
                          </table> 
                        </div>  
                      </div>
                    </div>  
                  </div>
                </form>
              </div>
            </div>
            <table class="table table-striped table-bordered table-dark">
             <thead>
              <tr>
               <th>Nombre</th>
               <th>Operaciones</th>
             </tr>
           </thead>
           <tbody>
            @foreach($UCS as $row)    
            <tr>
              <td>{{$row->nombres}} {{$row->apellidos}}</td>
              <td><a href="#">Detalles</a> <a href="#">Deshabilitar</a></td>
            </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
</div>
</body>
@jquery
@toastr_js
@toastr_render
</html>

Laravel/Tarea copia xD/hiro/resources/views/usuarios/create.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Nuevo Usuario</title>
	<!-- CSRF Token -->
	<meta name="csrf-token" content="{{ csrf_token() }}">

	<!-- Scripts -->
	<script src="{{ asset('js/app.js') }}"></script>

	<!-- Fonts -->
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

	<!-- Styles -->
	<link href="{{ asset('css/app.css') }}" rel="stylesheet">
	<link href="{{ asset('css/style.css') }}" rel="stylesheet">
	@toastr_css	
</head>
<body>
	@include('sweet::alert')	
	<nav class="navbar navbar-dark bg-dark navbar-expand-sm">
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-list-2" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbar-list-2">
			<ul class="navbar-nav">
				<li class="nav-item">
					<a class="nav-link" href="{{ route('usuarios.index') }}">Inicio <span class="sr-only">(current)</span></a>
				</li>
				<li class="nav-item dropdown active">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						Gestion alumno
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="{{ route('usuarios.create') }}">Registro de Alumnos</a>
						<a class="dropdown-item" href="#">Detalles de Alumnos</a>
					</div>
				</li>       
				<li class="nav-item">
					<a class="nav-link" href="{{ asset('/usuarios/consulta') }}">Consulta</a>
				</li>   
			</ul>
		</div>
	</nav>
	<br>
	<div class="d-flex justify-content-center">
		<div class="col-11">
			<div class="card mb-4">
				<!-- <div class="card-header"><i class="fas fa-table mr-1"></i>Registro de Alumnos</div> -->
				<div class="card-body">
					<form method="POST" action="{{ route('usuarios.store') }}">
						@csrf          	
						<div class="container-fluid">
							<div class="row">
								<div class="col-sm-5 col-md-6">
									<div class="form-group">
										<fieldset class="the-fieldset">
											<legend class="the-legend">Personales</legend>
											<table cellpadding="10" cellspacing="3">
												<tr>
													<td>Nombres:</td>
													<td width="100%"><input type="text" name="name" class="form-control"></td>
												</tr>
												<tr>
													<td>Apellidos:</td>
													<td><input type="text" name="lastname" class="form-control"></td>
												</tr>
												<tr>
													<td>Movil:</td>
													<td><input type="text" name="colonia" class="form-control" maxlength="9"></td>
												</tr>
												<tr>
													<td>Correo:</td>
													<td><input type="email" name="email" class="form-control"></td>
												</tr>					            	
											</table>
										</fieldset>
									</div>  	
								</div>
								<div class="col-sm-5 offset-sm-2 col-md-6 offset-md-0">
									<div class="form-group">
										<fieldset class="the-fieldset">
											<legend class="the-legend">Competencia</legend>
											<table cellpadding="10" cellspacing="3">
												<tr>
													<td>Nombre:</td>
													<td width="100%"><input type="text" name="competition" class="form-control"></td>
												</tr>
												<tr>
													<td>Descripcion:</td>
													<td><textarea name="description" class="form-control" rows="6"></textarea></td>
												</tr>																		
											</table>	            
										</fieldset>
									</div> 	
								</div>
							</div>	  	
						</div>
						<input type="submit" name="Enviar" value="Registrar" class="btn btn-primary float-right">
					</form>  				              	
				</div>
			</div>      
		</div>
	</div>
</body>
</html>

Laravel/Tarea copia xD/hiro/resources/views/usuarios/index.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Mostrar Usuarios</title>
  <!-- CSRF Token -->
  <meta name="csrf-token" content="{{ csrf_token() }}">

  <!-- Scripts -->
  <script src="{{ asset('js/app.js') }}"></script>

  <!-- Fonts -->
  <link rel="dns-prefetch" href="//fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

  <!-- Styles -->
  <link href="{{ asset('css/app.css') }}" rel="stylesheet">	
  <link href="{{ asset('css/style.css') }}" rel="stylesheet">	
</head>
<body> 
  <nav class="navbar navbar-dark bg-dark navbar-expand-sm">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-list-2" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar-list-2">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{{ route('usuarios.index') }}">Inicio <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Gestion alumno
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{{ route('usuarios.create') }}">Registro de Alumnos</a>
            <a class="dropdown-item" href="#">Detalles de Alumnos</a>
          </div>
        </li>       
        <li class="nav-item">
          <a class="nav-link" href="{{ asset('/usuarios/consulta') }}">Consulta</a>
        </li>   
      </ul>
    </div>
  </nav>
  <br>
  <div class="d-flex justify-content-center">
   <div class="col-11">
     <div class="jumbotron bg-cover text-white" style="background-image: linear-gradient(to bottom, rgba(0,0,0,0.6) 0%,rgba(0,0,0,0.6) 100%), url(https://placeimg.com/1000/480/nature)">
       <div class="container-jumbotron">
         <h1 class="display-4">Bienvenido, @Usuario!</h1>
       </div>
       <!-- /.container   -->
     </div>  
   </div>
 </div>	
</body>
</html>